version: "3.9"

services:
  backend:
    build: ./backend
    container_name: quiz_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: quiz_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
